sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: QE9PLwwVumhBOVbnPElnvxkkZex9MUUE3ZitaLUi6YvnchAv76VsXwjx9ImXrGEa+zKf+qkl1qM0Bt/noWv2DbDIfmzOLGW1qLlLWhDeMHsArFMcI9HqAqMFzjYPwiJzuey9rITGV9mqKfCE/z2kO8O5pi4nMIj7a8PkczEx7yWjRUSr/sWSRIayIw9jQbYhfeHaEBunGTbYym15aSQ1fXzmtksqHSXzAOopB/x9hh/MUiXUr1kYrpLPhqcfGZhHHQRuQpJ0AzTHBebNErOirGejV64nvNsG/PNAsZDjCQcAJWAxaMmEbtQHFKxf1r/XTn4apiqcHkAnlGnvWCBzoe/w45U/wK4cuAvaBF3IwQYT2bGKHOQwswZkggSxqwY5KrCQpU4JoeJpLiv4szAIdFVCzoIYlJExO5XN/69k43ShuD4FvK8b8IdH3SpH8+bQFFU4KIghHedr1De6WOhoJadkcH3J83PIpvkCqWaHqf5raXT+6/+J/NSOXG4uLm/iT4VJpfREwYTGE/6UF6BnSjiOmsrG8YwL4M9d+g/McsYQDi+9jWRMTwTn5HNg4Jc5uMdWC61/7Hi03zK7xEHQeN8z9VhIT2+qi0/zCLuVzcUcD83yLM9SyLftwJ9aqqpxW4kZOjx97AsHJg4zAHR3Ez3N35Eg5BoMLK0xfVf+IHI=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: JmsyqSsxSNL1sPD+itCgDyjaJ6t2fWdLl36MY/6ZK3ra+tiApqkDJB80h9RsQzW6oEyq4v8oD/69RWPXB8X4d1j4RB8/JxlYymGn4ZQSYxFMrEgAjhr4/1eUdei/0KE8H+us0NrwILWSycUbXj7l4ymc3qr9Y072UWS828DYIANy2BpO7k3LzsgF19Q4Rk7mqNJ+N58OXmWn5EcthIgtScY5BYsetKESQUWB0FKuEDaLcOWgZxG1eX3trad1IMSu/7zc7ELB0hWVi1WtqW4tbbt5o6o1f7FD0EnQeHhfr8kfCjGuPNgIrClYPlrppFOtW03RpNv8/XfwAhNCmY5v5v623zbNe3djJj+YTk1XmvvpTVtGLcVXvgZSxu5oU5+JxC5zY2d3Y26aitAR1n9SrcKT1jvbDKuLSnGDoVjyDhEghGZlCBQ3dpe+RvDg8iAUs+cswl0x/oc86f1r5ZcFXn4Dj/20SC+za1DMGALvmljn96er3p6wd0h/TjNS5wiq1Rm4a1htGIWlZ1lkSm9NfUKmfde1QaF3mggJVk9hg5ZsRhn7f60MaqG6hP3i6I72czjuzXRtFkRj7IPXamsKMdip7mUASFE/U+D11mkJMDsu9xCT500B67pUggbYT3v5xG9rDIsHH1+LSABnhWZ00KnE4D665JnAWeonNdHP8XA=
